'use strict';

const PDFDocument = require('pdfkit');
const logger = require('../utils/logger');

class ReportGenerator {
  constructor(db) {
    this.db = db;
  }

  /**
   * Generate a PDF compliance report.
   * @param {object} options - Report options
   * @returns {Buffer} PDF buffer
   */
  async generateReport(options = {}) {
    const {
      deviceId,
      baselineId,
      framework,
      platform,
      includeDeviceBreakdown = true,
      includeRemediations = true,
      includeHistory = true,
      title,
    } = options;

    logger.info('Generating compliance report', { deviceId, baselineId, framework });

    // Gather report data
    const reportData = await this._gatherReportData(options);

    // Build PDF
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margins: { top: 50, bottom: 50, left: 50, right: 50 },
          info: {
            Title: title || 'Compliance Report',
            Author: 'OpenDirectory Compliance Engine',
            Subject: 'Compliance Evaluation Report',
            CreationDate: new Date(),
          },
        });

        const buffers = [];
        doc.on('data', chunk => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        // Title page
        this._renderTitlePage(doc, reportData, title);

        // Executive summary
        doc.addPage();
        this._renderExecutiveSummary(doc, reportData);

        // Score overview
        this._renderScoreOverview(doc, reportData);

        // Per-baseline breakdown
        if (includeDeviceBreakdown && reportData.baselines) {
          for (const baseline of reportData.baselines) {
            doc.addPage();
            this._renderBaselineSection(doc, baseline, includeRemediations);
          }
        }

        // Compliance history / trend
        if (includeHistory && reportData.history) {
          doc.addPage();
          this._renderHistorySection(doc, reportData.history);
        }

        // Regulatory mapping
        if (reportData.regulatoryMapping) {
          doc.addPage();
          this._renderRegulatoryMapping(doc, reportData.regulatoryMapping);
        }

        // Footer with generation timestamp
        const totalPages = doc.bufferedPageRange();
        for (let i = 0; i < totalPages.count; i++) {
          doc.switchToPage(i);
          doc.fontSize(8).fillColor('#888888');
          doc.text(
            `Generated by OpenDirectory Compliance Engine | ${new Date().toISOString()} | Page ${i + 1} of ${totalPages.count}`,
            50, doc.page.height - 30,
            { align: 'center', width: doc.page.width - 100 }
          );
        }

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  async _gatherReportData(options) {
    const data = {
      generatedAt: new Date().toISOString(),
      baselines: [],
      history: null,
      regulatoryMapping: null,
    };

    if (options.deviceId) {
      // Single device report
      data.type = 'device';
      data.deviceId = options.deviceId;

      const { rows: results } = await this.db.query(
        `SELECT cr.*, cb.name AS baseline_name, cb.framework, cb.platform
         FROM compliance_results cr
         JOIN compliance_baselines cb ON cr.baseline_id = cb.id
         WHERE cr.device_id = $1
           AND cr.scanned_at = (
             SELECT MAX(scanned_at) FROM compliance_results
             WHERE device_id = $1 AND baseline_id = cr.baseline_id
           )
         ORDER BY cb.framework, cb.name`,
        [options.deviceId]
      );

      data.baselines = results.map(r => ({
        baselineId: r.baseline_id,
        baselineName: r.baseline_name,
        framework: r.framework,
        platform: r.platform,
        score: parseFloat(r.score),
        totalChecks: r.total_checks,
        passedChecks: r.passed_checks,
        failedChecks: r.failed_checks,
        skippedChecks: r.skipped_checks,
        criticalFailures: r.critical_failures,
        highFailures: r.high_failures,
        mediumFailures: r.medium_failures,
        lowFailures: r.low_failures,
        details: r.details || [],
        scannedAt: r.scanned_at,
      }));

      data.overallScore = data.baselines.length > 0
        ? parseFloat((data.baselines.reduce((s, b) => s + b.score, 0) / data.baselines.length).toFixed(2))
        : 0;

      // Get history
      if (options.includeHistory !== false) {
        const { rows: historyRows } = await this.db.query(
          `SELECT baseline_id, score, delta, recorded_at
           FROM compliance_history
           WHERE device_id = $1 AND recorded_at >= NOW() - INTERVAL '90 days'
           ORDER BY recorded_at ASC`,
          [options.deviceId]
        );
        data.history = historyRows;
      }
    } else {
      // Fleet-wide report
      data.type = 'fleet';

      let baselineFilter = '';
      const params = [];

      if (options.framework) {
        params.push(options.framework);
        baselineFilter += ` AND cb.framework = $${params.length}`;
      }
      if (options.platform) {
        params.push(options.platform);
        baselineFilter += ` AND cb.platform = $${params.length}`;
      }

      const { rows: fleetResults } = await this.db.query(
        `SELECT
           cb.id AS baseline_id, cb.name AS baseline_name, cb.framework, cb.platform,
           COUNT(DISTINCT cr.device_id) AS device_count,
           AVG(cr.score) AS avg_score,
           MIN(cr.score) AS min_score,
           MAX(cr.score) AS max_score,
           SUM(cr.critical_failures) AS total_critical,
           SUM(cr.high_failures) AS total_high,
           SUM(cr.failed_checks) AS total_failures
         FROM compliance_results cr
         JOIN compliance_baselines cb ON cr.baseline_id = cb.id
         WHERE cr.scanned_at = (
           SELECT MAX(scanned_at) FROM compliance_results
           WHERE device_id = cr.device_id AND baseline_id = cr.baseline_id
         ) ${baselineFilter}
         GROUP BY cb.id, cb.name, cb.framework, cb.platform
         ORDER BY cb.framework, cb.name`,
        params
      );

      data.baselines = fleetResults.map(r => ({
        baselineId: r.baseline_id,
        baselineName: r.baseline_name,
        framework: r.framework,
        platform: r.platform,
        deviceCount: parseInt(r.device_count, 10),
        averageScore: parseFloat(parseFloat(r.avg_score).toFixed(2)),
        minScore: parseFloat(parseFloat(r.min_score).toFixed(2)),
        maxScore: parseFloat(parseFloat(r.max_score).toFixed(2)),
        totalCriticalFailures: parseInt(r.total_critical, 10),
        totalHighFailures: parseInt(r.total_high, 10),
        totalFailures: parseInt(r.total_failures, 10),
      }));

      const scores = data.baselines.map(b => b.averageScore);
      data.overallScore = scores.length > 0
        ? parseFloat((scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(2))
        : 0;
    }

    // Regulatory mapping (framework -> controls)
    data.regulatoryMapping = this._getFrameworkMapping(options.framework);

    return data;
  }

  _renderTitlePage(doc, data, customTitle) {
    doc.moveDown(8);
    doc.fontSize(28).fillColor('#1a1a2e').text(customTitle || 'Compliance Report', { align: 'center' });
    doc.moveDown(1);
    doc.fontSize(14).fillColor('#555555').text('OpenDirectory Compliance Engine', { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(12).fillColor('#333333');
    if (data.deviceId) {
      doc.text(`Device: ${data.deviceId}`, { align: 'center' });
    } else {
      doc.text('Fleet-Wide Compliance Assessment', { align: 'center' });
    }
    doc.moveDown(1);
    doc.fontSize(10).fillColor('#666666').text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.text(`Baselines Evaluated: ${data.baselines.length}`, { align: 'center' });
  }

  _renderExecutiveSummary(doc, data) {
    doc.fontSize(18).fillColor('#1a1a2e').text('Executive Summary');
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
    doc.moveDown(1);

    const scoreColor = data.overallScore >= 90 ? '#27ae60' :
                        data.overallScore >= 70 ? '#f39c12' :
                        data.overallScore >= 50 ? '#e67e22' : '#e74c3c';

    doc.fontSize(36).fillColor(scoreColor).text(`${data.overallScore}%`, { align: 'center' });
    doc.fontSize(12).fillColor('#666666').text('Overall Compliance Score', { align: 'center' });
    doc.moveDown(2);

    const status = data.overallScore >= 90 ? 'COMPLIANT' :
                   data.overallScore >= 70 ? 'PARTIALLY COMPLIANT' :
                   data.overallScore >= 50 ? 'AT RISK' : 'NON-COMPLIANT';

    doc.fontSize(14).fillColor(scoreColor).text(`Status: ${status}`, { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(11).fillColor('#333333');
    doc.text(`Report Type: ${data.type === 'device' ? 'Device Assessment' : 'Fleet Assessment'}`);
    doc.text(`Baselines Evaluated: ${data.baselines.length}`);
    doc.text(`Report Generated: ${data.generatedAt}`);
  }

  _renderScoreOverview(doc, data) {
    doc.moveDown(2);
    doc.fontSize(16).fillColor('#1a1a2e').text('Score Overview by Baseline');
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
    doc.moveDown(1);

    for (const baseline of data.baselines) {
      const score = baseline.score || baseline.averageScore || 0;
      const scoreColor = score >= 90 ? '#27ae60' : score >= 70 ? '#f39c12' : '#e74c3c';

      doc.fontSize(11).fillColor('#333333').text(`${baseline.baselineName}`, { continued: true });
      doc.fillColor(scoreColor).text(`  ${score}%`, { align: 'right' });

      // Simple bar
      const barWidth = 400;
      const filledWidth = (score / 100) * barWidth;
      const barY = doc.y + 2;
      doc.rect(50, barY, barWidth, 8).fill('#eeeeee');
      doc.rect(50, barY, filledWidth, 8).fill(scoreColor);
      doc.moveDown(1);

      if (doc.y > doc.page.height - 100) {
        doc.addPage();
      }
    }
  }

  _renderBaselineSection(doc, baseline, includeRemediations) {
    const score = baseline.score || baseline.averageScore || 0;

    doc.fontSize(16).fillColor('#1a1a2e').text(baseline.baselineName);
    doc.fontSize(10).fillColor('#888888').text(`Framework: ${(baseline.framework || '').toUpperCase()} | Platform: ${baseline.platform || 'all'}`);
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
    doc.moveDown(1);

    doc.fontSize(24).fillColor(score >= 90 ? '#27ae60' : score >= 70 ? '#f39c12' : '#e74c3c');
    doc.text(`${score}%`);
    doc.moveDown(0.5);

    if (baseline.totalChecks !== undefined) {
      doc.fontSize(10).fillColor('#333333');
      doc.text(`Total Checks: ${baseline.totalChecks} | Passed: ${baseline.passedChecks} | Failed: ${baseline.failedChecks} | Skipped: ${baseline.skippedChecks || 0}`);
      doc.text(`Critical Failures: ${baseline.criticalFailures || 0} | High: ${baseline.highFailures || 0} | Medium: ${baseline.mediumFailures || 0} | Low: ${baseline.lowFailures || 0}`);
    }

    // Detail checks if available
    if (baseline.details && Array.isArray(baseline.details)) {
      doc.moveDown(1);
      doc.fontSize(12).fillColor('#1a1a2e').text('Check Results:');
      doc.moveDown(0.5);

      for (const check of baseline.details) {
        if (doc.y > doc.page.height - 100) {
          doc.addPage();
        }

        const icon = check.passed ? 'PASS' : check.waived ? 'WAIVED' : check.skipped ? 'SKIP' : 'FAIL';
        const color = check.passed ? '#27ae60' : check.waived ? '#3498db' : check.skipped ? '#95a5a6' : '#e74c3c';

        doc.fontSize(9).fillColor(color).text(`[${icon}]`, { continued: true });
        doc.fillColor('#333333').text(` ${check.title || check.checkId}`);

        if (!check.passed && !check.skipped && !check.waived && includeRemediations) {
          doc.fontSize(8).fillColor('#888888').text(`    Expected: ${JSON.stringify(check.expected)} | Actual: ${JSON.stringify(check.actual)}`);
        }
      }
    }
  }

  _renderHistorySection(doc, history) {
    doc.fontSize(16).fillColor('#1a1a2e').text('Compliance History (Last 90 Days)');
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
    doc.moveDown(1);

    if (!history || history.length === 0) {
      doc.fontSize(10).fillColor('#888888').text('No historical data available.');
      return;
    }

    // Tabular history
    doc.fontSize(9).fillColor('#333333');
    doc.text('Date                    Score     Delta', { underline: true });
    doc.moveDown(0.3);

    for (const entry of history.slice(-30)) {
      if (doc.y > doc.page.height - 60) {
        doc.addPage();
      }

      const date = new Date(entry.recorded_at).toLocaleDateString();
      const delta = parseFloat(entry.delta);
      const deltaStr = delta >= 0 ? `+${delta}` : `${delta}`;
      const deltaColor = delta > 0 ? '#27ae60' : delta < 0 ? '#e74c3c' : '#888888';

      doc.fillColor('#333333').text(`${date}`, 50, doc.y, { continued: true, width: 150 });
      doc.text(`${parseFloat(entry.score).toFixed(1)}%`, { continued: true, width: 80 });
      doc.fillColor(deltaColor).text(`  ${deltaStr}%`);
    }
  }

  _renderRegulatoryMapping(doc, mapping) {
    if (!mapping) return;

    doc.fontSize(16).fillColor('#1a1a2e').text('Regulatory Framework Mapping');
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
    doc.moveDown(1);

    doc.fontSize(10).fillColor('#333333');
    for (const [framework, controls] of Object.entries(mapping)) {
      if (doc.y > doc.page.height - 100) {
        doc.addPage();
      }
      doc.fontSize(12).fillColor('#1a1a2e').text(framework.toUpperCase());
      doc.moveDown(0.3);
      for (const control of controls) {
        doc.fontSize(9).fillColor('#555555').text(`  ${control.id}: ${control.description}`);
      }
      doc.moveDown(0.5);
    }
  }

  _getFrameworkMapping(framework) {
    const mappings = {
      cis: [
        { id: 'CIS 1', description: 'Inventory and Control of Enterprise Assets' },
        { id: 'CIS 2', description: 'Inventory and Control of Software Assets' },
        { id: 'CIS 3', description: 'Data Protection' },
        { id: 'CIS 4', description: 'Secure Configuration of Enterprise Assets and Software' },
        { id: 'CIS 5', description: 'Account Management' },
        { id: 'CIS 6', description: 'Access Control Management' },
      ],
      nist: [
        { id: 'AC', description: 'Access Control' },
        { id: 'AU', description: 'Audit and Accountability' },
        { id: 'CM', description: 'Configuration Management' },
        { id: 'IA', description: 'Identification and Authentication' },
        { id: 'SC', description: 'System and Communications Protection' },
        { id: 'SI', description: 'System and Information Integrity' },
      ],
      iso27001: [
        { id: 'A.5', description: 'Information Security Policies' },
        { id: 'A.6', description: 'Organization of Information Security' },
        { id: 'A.8', description: 'Asset Management' },
        { id: 'A.9', description: 'Access Control' },
        { id: 'A.10', description: 'Cryptography' },
        { id: 'A.12', description: 'Operations Security' },
      ],
      dsgvo: [
        { id: 'Art. 25', description: 'Data protection by design and by default' },
        { id: 'Art. 32', description: 'Security of processing' },
        { id: 'Art. 33', description: 'Notification of a personal data breach' },
        { id: 'Art. 35', description: 'Data protection impact assessment' },
      ],
    };

    if (framework && mappings[framework]) {
      return { [framework]: mappings[framework] };
    }
    return mappings;
  }
}

module.exports = ReportGenerator;
