{{- if and .Values.postgresql.enabled .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opendirectory.fullname" . }}-postgresql
  namespace: {{ include "opendirectory.namespace" . }}
  labels:
    {{- include "opendirectory.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.storageClass }}
  storageClassName: {{ .Values.postgresql.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opendirectory.fullname" . }}-backup-storage
  namespace: {{ include "opendirectory.namespace" . }}
  labels:
    {{- include "opendirectory.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backupStorageSize }}
{{- end }}
{{- end }}
