'use strict';

// ─── Lenovo Driver Provider ───────────────────────────────────────────────────
// All Lenovo device driver entries — Windows and Linux.

const DRIVERS = [
  // ── Windows ──────────────────────────────────────────────────────────────────

  {
    id: 'lenovo-net-i219-win',
    name: 'Lenovo ThinkPad Intel I219-LM Ethernet Driver',
    version: '12.19.2.36',
    vendor: 'Lenovo',
    os: ['windows'],
    deviceType: 'network',
    format: 'exe',
    architecture: 'x86_64',
    description: 'Intel I219-LM Gigabit Ethernet driver for ThinkPad docking and LAN',
    downloadUrl: 'https://download.lenovo.com/pccbbs/mobiles/r0xne05w.exe',
    models: ['ThinkPad T14 Gen 3', 'ThinkPad L14 Gen 3', 'ThinkPad E14 Gen 4', 'ThinkPad T16 Gen 1'],
    tags: ['network', 'ethernet', 'intel', 'i219'],
    licenseType: 'freeware',
  },
  {
    id: 'lenovo-wifi-ax211-win',
    name: 'Lenovo ThinkPad Intel Wi-Fi 6E AX211 Driver',
    version: '22.230.0.8',
    vendor: 'Lenovo',
    os: ['windows'],
    deviceType: 'network',
    format: 'exe',
    architecture: 'x86_64',
    description: 'Intel Wi-Fi 6E AX211 driver — 6 GHz band support for ThinkPad',
    downloadUrl: 'https://download.lenovo.com/pccbbs/mobiles/r1xwf10w.exe',
    models: ['ThinkPad X1 Carbon Gen 10', 'ThinkPad T14s Gen 3', 'ThinkPad T16 Gen 1'],
    tags: ['wifi', 'intel', 'ax211', '6e', '6ghz'],
    licenseType: 'freeware',
  },
  {
    id: 'lenovo-audio-realtek-win',
    name: 'Lenovo ThinkPad Realtek Audio Driver',
    version: '6.0.9374.1',
    vendor: 'Lenovo',
    os: ['windows'],
    deviceType: 'audio',
    format: 'exe',
    architecture: 'x86_64',
    description: 'Realtek HD Audio driver for ThinkPad series',
    downloadUrl: 'https://download.lenovo.com/pccbbs/mobiles/r0xau12w.exe',
    models: ['ThinkPad T14 Gen 3', 'ThinkPad X1 Carbon Gen 10', 'ThinkPad L14 Gen 3'],
    tags: ['audio', 'realtek', 'hda', 'thinkpad'],
    licenseType: 'freeware',
  },
  {
    id: 'lenovo-display-iris-win',
    name: 'Lenovo ThinkPad Intel Iris Xe Graphics Driver',
    version: '31.0.101.2115',
    vendor: 'Lenovo',
    os: ['windows'],
    deviceType: 'display',
    format: 'exe',
    architecture: 'x86_64',
    description: 'Intel Iris Xe Graphics driver for ThinkPad 12th gen Intel platforms',
    downloadUrl: 'https://download.lenovo.com/pccbbs/mobiles/r1xvd04w.exe',
    models: ['ThinkPad X1 Carbon Gen 10', 'ThinkPad T14s Gen 3', 'ThinkPad T14 Gen 3'],
    tags: ['display', 'intel', 'iris', 'xe', 'igpu'],
    licenseType: 'freeware',
  },
  {
    id: 'lenovo-fingerprint-win',
    name: 'Lenovo ThinkPad Fingerprint Reader Driver',
    version: '10.0.19041.10027',
    vendor: 'Lenovo',
    os: ['windows'],
    deviceType: 'biometric',
    format: 'exe',
    architecture: 'x86_64',
    description: 'Synaptics fingerprint reader driver for ThinkPad (Windows Hello)',
    downloadUrl: 'https://download.lenovo.com/pccbbs/mobiles/r0xfp04w.exe',
    models: ['ThinkPad T14 Gen 3', 'ThinkPad X1 Carbon Gen 10', 'ThinkPad T16 Gen 1'],
    tags: ['fingerprint', 'biometric', 'synaptics', 'windows-hello'],
    licenseType: 'freeware',
  },
  {
    id: 'lenovo-bios-t14g3-win',
    name: 'Lenovo ThinkPad T14 Gen 3 BIOS Update',
    version: '1.47',
    vendor: 'Lenovo',
    os: ['windows'],
    deviceType: 'firmware',
    format: 'exe',
    architecture: 'x86_64',
    description: 'BIOS update for ThinkPad T14 Gen 3 AMD — security and stability',
    downloadUrl: 'https://download.lenovo.com/pccbbs/mobiles/r1xuj19w.exe',
    models: ['ThinkPad T14 Gen 3'],
    tags: ['bios', 'firmware', 'thinkpad'],
    licenseType: 'freeware',
  },
  {
    id: 'lenovo-thunderbolt4-win',
    name: 'Lenovo ThinkPad Thunderbolt 4 Dock Driver',
    version: '1.0.5.1',
    vendor: 'Lenovo',
    os: ['windows'],
    deviceType: 'usb',
    format: 'exe',
    architecture: 'x86_64',
    description: 'ThinkPad Thunderbolt 4 Dock (40B0) driver and firmware',
    downloadUrl: 'https://download.lenovo.com/pccbbs/options/tp4dock_fw_v1.0.5.1.exe',
    models: ['ThinkPad Thunderbolt 4 Dock Gen 2'],
    tags: ['thunderbolt', 'dock', 'usb4', 'hub'],
    licenseType: 'freeware',
  },
  {
    id: 'lenovo-camera-win',
    name: 'Lenovo ThinkPad IR & RGB Camera Driver',
    version: '11.3.6.2021',
    vendor: 'Lenovo',
    os: ['windows'],
    deviceType: 'camera',
    format: 'exe',
    architecture: 'x86_64',
    description: 'IR and RGB webcam driver for Windows Hello facial recognition',
    downloadUrl: 'https://download.lenovo.com/pccbbs/mobiles/r0xcm09w.exe',
    models: ['ThinkPad X1 Carbon Gen 10', 'ThinkPad T14 Gen 3'],
    tags: ['camera', 'webcam', 'ir', 'windows-hello'],
    licenseType: 'freeware',
  },

  // ── Linux ─────────────────────────────────────────────────────────────────────

  {
    id: 'lenovo-fwupd-linux',
    name: 'Lenovo ThinkPad Firmware Update (fwupd / LVFS)',
    version: 'latest',
    vendor: 'Lenovo',
    os: ['linux'],
    deviceType: 'firmware',
    format: 'deb',
    architecture: 'universal',
    description: 'BIOS, EC and embedded controller firmware via LVFS — ThinkPad / IdeaPad',
    downloadUrl: '',
    models: ['ThinkPad T14 Gen 3', 'ThinkPad X1 Carbon Gen 10', 'ThinkPad L14 Gen 3'],
    aptPackage: 'fwupd',
    tags: ['firmware', 'fwupd', 'lvfs', 'bios', 'thinkpad'],
    licenseType: 'open-source',
  },
  {
    id: 'lenovo-wifi-linux',
    name: 'Lenovo ThinkPad Intel WiFi Firmware (iwlwifi)',
    version: 'latest',
    vendor: 'Lenovo',
    os: ['linux'],
    deviceType: 'network',
    format: 'deb',
    architecture: 'universal',
    description: 'Intel iwlwifi firmware for ThinkPad AX200 / AX210 / AX211 wireless',
    downloadUrl: '',
    models: ['ThinkPad X1 Carbon Gen 10', 'ThinkPad T14s Gen 3', 'ThinkPad T14 Gen 3'],
    aptPackage: 'firmware-iwlwifi',
    tags: ['wifi', 'intel', 'iwlwifi', 'ax210', 'ax211', 'linux'],
    licenseType: 'open-source',
  },
  {
    id: 'lenovo-audio-alsa-linux',
    name: 'Lenovo ThinkPad HD Audio (ALSA / snd-hda)',
    version: 'latest',
    vendor: 'Lenovo',
    os: ['linux'],
    deviceType: 'audio',
    format: 'deb',
    architecture: 'universal',
    description: 'ALSA firmware for Realtek audio codec on ThinkPad',
    downloadUrl: '',
    models: ['ThinkPad T14 Gen 3', 'ThinkPad X1 Carbon Gen 10'],
    aptPackage: 'alsa-firmware-loaders',
    tags: ['audio', 'realtek', 'alsa', 'thinkpad', 'linux'],
    licenseType: 'open-source',
  },
  {
    id: 'lenovo-tpsmapi-linux',
    name: 'ThinkPad ACPI / Battery Management (tp-smapi)',
    version: 'latest',
    vendor: 'Lenovo',
    os: ['linux'],
    deviceType: 'other',
    format: 'deb',
    architecture: 'universal',
    description: 'tp-smapi DKMS module — battery charge control, power management for ThinkPad',
    downloadUrl: '',
    models: ['ThinkPad T14 Gen 3', 'ThinkPad X1 Carbon Gen 10', 'ThinkPad L14 Gen 3'],
    aptPackage: 'tp-smapi-dkms',
    tags: ['thinkpad', 'acpi', 'battery', 'power', 'dkms', 'linux'],
    licenseType: 'open-source',
  },
];

function getDrivers() {
  return DRIVERS;
}

module.exports = { getDrivers };
