ALTER TABLE devices ADD COLUMN IF NOT EXISTS os TEXT;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS os_version TEXT;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS kernel TEXT;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS package_manager TEXT;
