'use strict';

const APP_CATALOG = [
  {
    id: 'github-enterprise',
    name: 'GitHub Enterprise',
    logo: '🐙',
    category: 'Developer Tools',
    protocol: 'oidc',
    description: 'OIDC SSO integration for GitHub Enterprise Server. Users authenticate via OpenDirectory.',
    setupSteps: [
      'Go to GitHub Enterprise Admin → Authentication → SAML/OIDC',
      'Set Authorization Callback URL to your GHES instance',
      'Copy Client ID and Client Secret from OpenDirectory',
      'Configure issuer URL to point to your OpenDirectory instance',
      'Test login with a test user',
    ],
    defaultScopes: ['openid', 'profile', 'email', 'groups'],
    defaultRedirectUriPattern: 'https://github.example.com/users/auth/openid_connect/callback',
    configTemplate: {
      issuer: 'https://opendirectory.local',
      client_id: '<CLIENT_ID>',
      client_secret: '<CLIENT_SECRET>',
      scopes: 'openid profile email',
    },
    documentationUrl: 'https://docs.github.com/en/enterprise-server/admin/identity-and-access-management/using-saml-for-enterprise-iam',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    logo: '🦊',
    category: 'Developer Tools',
    protocol: 'saml',
    description: 'SAML SSO for GitLab. Enables group-based access control from OpenDirectory.',
    setupSteps: [
      'Go to GitLab Admin → Settings → SAML',
      'Set Assertion Consumer Service URL',
      'Copy IDP metadata from /saml/metadata',
      'Map SAML attributes to GitLab user fields',
      'Enable group sync via SAML groups attribute',
    ],
    defaultScopes: [],
    defaultRedirectUriPattern: 'https://gitlab.example.com/users/auth/saml/callback',
    configTemplate: {
      idp_sso_url: 'https://opendirectory.local/saml/sso',
      idp_cert_fingerprint: '<SHA1_FINGERPRINT>',
      attribute_statements: { email: ['email'], first_name: ['firstName'], last_name: ['lastName'] },
    },
    documentationUrl: 'https://docs.gitlab.com/ee/integration/saml.html',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    logo: '📊',
    category: 'Monitoring',
    protocol: 'oidc',
    description: 'generic_oauth integration for Grafana. Map directory groups to Grafana org roles.',
    setupSteps: [
      'Edit grafana.ini [auth.generic_oauth] section',
      'Set client_id and client_secret',
      'Configure scopes: openid profile email groups',
      'Set role_attribute_path for group-based role mapping',
      'Restart Grafana service',
    ],
    defaultScopes: ['openid', 'profile', 'email', 'groups'],
    defaultRedirectUriPattern: 'https://grafana.example.com/login/generic_oauth',
    configTemplate: {
      enabled: true,
      name: 'OpenDirectory',
      allow_sign_up: true,
      client_id: '<CLIENT_ID>',
      client_secret: '<CLIENT_SECRET>',
      scopes: 'openid profile email groups',
      auth_url: 'https://opendirectory.local/oauth/authorize',
      token_url: 'https://opendirectory.local/oauth/token',
      api_url: 'https://opendirectory.local/oauth/userinfo',
      role_attribute_path: "contains(groups[*], 'grafana-admin') && 'Admin' || 'Viewer'",
    },
    documentationUrl: 'https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/',
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    logo: '☁️',
    category: 'Productivity',
    protocol: 'oidc',
    description: 'OIDC social login for Nextcloud using the social_login app.',
    setupSteps: [
      'Install the "Social Login" app from Nextcloud App Store',
      'Go to Settings → Social Login',
      'Add new OpenID Connect provider',
      'Enter Client ID, Client Secret, and discovery URL',
      'Enable "Disable auto create new users" if needed',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://nextcloud.example.com/apps/social_login/custom_oidc/<PROVIDER_NAME>',
    configTemplate: {
      title: 'OpenDirectory',
      authorize_url: 'https://opendirectory.local/oauth/authorize',
      token_url: 'https://opendirectory.local/oauth/token',
      user_info_url: 'https://opendirectory.local/oauth/userinfo',
      client_id: '<CLIENT_ID>',
      client_secret: '<CLIENT_SECRET>',
      scope: 'openid profile email',
    },
    documentationUrl: 'https://github.com/zorn-v/nextcloud-social-login',
  },
  {
    id: 'mattermost',
    name: 'Mattermost',
    logo: '💬',
    category: 'Collaboration',
    protocol: 'oidc',
    description: 'OIDC-based SSO for Mattermost self-hosted. Enables auto-provisioning of users.',
    setupSteps: [
      'Go to System Console → Authentication → OpenID Connect',
      'Select "Other" as provider',
      'Enter Discovery Endpoint URL',
      'Set Client ID and Client Secret',
      'Configure button name and icon',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://mattermost.example.com/signup/openid/complete',
    configTemplate: {
      Enable: true,
      DiscoveryEndpoint: 'https://opendirectory.local/.well-known/openid-configuration',
      Id: '<CLIENT_ID>',
      Secret: '<CLIENT_SECRET>',
      ButtonText: 'Login with OpenDirectory',
    },
    documentationUrl: 'https://docs.mattermost.com/onboard/sso-openidconnect.html',
  },
  {
    id: 'jira-confluence',
    name: 'Jira / Confluence',
    logo: '📋',
    category: 'Project Management',
    protocol: 'saml',
    description: 'SAML 2.0 SSO for Atlassian Data Center products (Jira, Confluence).',
    setupSteps: [
      'Go to Administration → User Management → SAML SSO',
      'Download metadata from /saml/metadata',
      'Enter Single Sign On URL and Identity Provider Entity ID',
      'Upload or paste the IdP certificate',
      'Configure user attribute mappings',
    ],
    defaultScopes: [],
    defaultRedirectUriPattern: 'https://jira.example.com/plugins/servlet/saml/auth',
    configTemplate: {
      sso_url: 'https://opendirectory.local/saml/sso',
      entity_id: 'https://opendirectory.local',
      name_id_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
      attribute_email: 'email',
      attribute_firstname: 'firstName',
      attribute_lastname: 'lastName',
    },
    documentationUrl: 'https://confluence.atlassian.com/doc/configuring-saml-single-sign-on-for-atlassian-data-center-applications',
  },
  {
    id: 'aws-iam-identity-center',
    name: 'AWS IAM Identity Center',
    logo: '☁',
    category: 'Cloud',
    protocol: 'saml',
    description: 'SAML federation between OpenDirectory and AWS IAM Identity Center (formerly SSO).',
    setupSteps: [
      'Go to IAM Identity Center → Settings → Identity Source',
      'Choose "External identity provider"',
      'Upload the IdP SAML metadata from /saml/metadata',
      'Download the SP metadata and configure the SAML app in OpenDirectory',
      'Map user attributes: email, firstName, lastName',
      'Assign users/groups to AWS account permission sets',
    ],
    defaultScopes: [],
    defaultRedirectUriPattern: 'https://signin.aws.amazon.com/saml',
    configTemplate: {
      idp_metadata_url: 'https://opendirectory.local/saml/metadata',
      attribute_email: '${user:email}',
      attribute_subject: '${user:preferred_username}',
    },
    documentationUrl: 'https://docs.aws.amazon.com/singlesignon/latest/userguide/manage-your-identity-source-idp.html',
  },
  {
    id: 'portainer',
    name: 'Portainer',
    logo: '🐳',
    category: 'Infrastructure',
    protocol: 'oauth2',
    description: 'OAuth2 integration for Portainer container management. Enables team-based access.',
    setupSteps: [
      'Go to Portainer Settings → Authentication → OAuth',
      'Select "Custom" provider',
      'Enter Authorization URL, Access Token URL, Resource URL',
      'Set Client ID and Client Secret',
      'Configure scopes and user identifier',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://portainer.example.com',
    configTemplate: {
      ClientId: '<CLIENT_ID>',
      ClientSecret: '<CLIENT_SECRET>',
      AuthorizationURI: 'https://opendirectory.local/oauth/authorize',
      AccessTokenURI: 'https://opendirectory.local/oauth/token',
      ResourceURI: 'https://opendirectory.local/oauth/userinfo',
      Scopes: 'openid profile email',
      UserIdentifier: 'preferred_username',
    },
    documentationUrl: 'https://docs.portainer.io/admin/settings/authentication/oauth',
  },
  {
    id: 'proxmox-ve',
    name: 'Proxmox VE',
    logo: '🖥️',
    category: 'Infrastructure',
    protocol: 'oidc',
    description: 'OIDC realm configuration for Proxmox VE. Users authenticate via OpenDirectory.',
    setupSteps: [
      'Go to Datacenter → Realm → Add → OpenID Connect',
      'Set Issuer URL to your OpenDirectory instance',
      'Enter Client ID and Client Secret',
      'Configure username claim (preferred_username)',
      'Optionally sync groups for auto-ACL assignment',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://proxmox.example.com:8006',
    configTemplate: {
      issuer_url: 'https://opendirectory.local',
      client_id: '<CLIENT_ID>',
      client_key: '<CLIENT_SECRET>',
      username_claim: 'preferred_username',
      scopes: 'openid profile email',
      autocreate: 1,
    },
    documentationUrl: 'https://pve.proxmox.com/wiki/OpenID_Connect',
  },
  {
    id: 'rancher',
    name: 'Rancher',
    logo: '🤠',
    category: 'Infrastructure',
    protocol: 'oidc',
    description: 'OIDC auth provider for Rancher Kubernetes Management. Maps groups to cluster roles.',
    setupSteps: [
      'Go to Global Settings → Configuration → Authentication',
      'Choose "Keycloak (OIDC)" or "Generic OIDC"',
      'Enter Client ID, Client Secret, and issuer URL',
      'Set Rancher URL as the authorized redirect URI',
      'Configure group sync for RBAC',
    ],
    defaultScopes: ['openid', 'profile', 'email', 'groups'],
    defaultRedirectUriPattern: 'https://rancher.example.com/verify-auth',
    configTemplate: {
      issuer: 'https://opendirectory.local',
      clientId: '<CLIENT_ID>',
      clientSecret: '<CLIENT_SECRET>',
      rancherUrl: 'https://rancher.example.com',
      scope: 'openid profile email groups',
    },
    documentationUrl: 'https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-openldap',
  },
  {
    id: 'kubernetes-api',
    name: 'Kubernetes API Server',
    logo: '⚙️',
    category: 'Infrastructure',
    protocol: 'oidc',
    description: 'Configure the Kubernetes API server with --oidc-issuer-url flags for RBAC via groups.',
    setupSteps: [
      'Add OIDC flags to kube-apiserver manifest',
      'Set --oidc-issuer-url to your OpenDirectory ISSUER',
      'Set --oidc-client-id to the Kubernetes client',
      'Configure --oidc-username-claim=preferred_username',
      'Configure --oidc-groups-claim=groups',
      'Create ClusterRoleBinding for groups',
    ],
    defaultScopes: ['openid', 'profile', 'email', 'groups'],
    defaultRedirectUriPattern: 'http://localhost:8000',
    configTemplate: {
      '--oidc-issuer-url': 'https://opendirectory.local',
      '--oidc-client-id': 'kubernetes',
      '--oidc-username-claim': 'preferred_username',
      '--oidc-groups-claim': 'groups',
      '--oidc-ca-file': '/etc/kubernetes/pki/oidc-ca.pem',
    },
    documentationUrl: 'https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens',
  },
  {
    id: 'hashicorp-vault',
    name: 'HashiCorp Vault',
    logo: '🔐',
    category: 'Security',
    protocol: 'oidc',
    description: 'JWT/OIDC auth method for HashiCorp Vault. Map directory groups to Vault policies.',
    setupSteps: [
      'Enable OIDC auth: vault auth enable oidc',
      'Configure OIDC: vault write auth/oidc/config oidc_discovery_url=...',
      'Create role: vault write auth/oidc/role/default bound_audiences=vault ...',
      'Map groups: vault write identity/group/...',
      'Test login: vault login -method=oidc',
    ],
    defaultScopes: ['openid', 'profile', 'email', 'groups'],
    defaultRedirectUriPattern: 'https://vault.example.com:8200/ui/vault/auth/oidc/oidc/callback',
    configTemplate: {
      oidc_discovery_url: 'https://opendirectory.local',
      oidc_client_id: '<CLIENT_ID>',
      oidc_client_secret: '<CLIENT_SECRET>',
      default_role: 'default',
    },
    documentationUrl: 'https://developer.hashicorp.com/vault/docs/auth/jwt',
  },
  {
    id: 'netdata',
    name: 'Netdata',
    logo: '📈',
    category: 'Monitoring',
    protocol: 'oidc',
    description: 'OIDC sign-in for Netdata Cloud or self-hosted Netdata Agent.',
    setupSteps: [
      'Edit netdata.conf [auth] section',
      'Set oidc_discovery_url',
      'Configure client_id and client_secret',
      'Set allowed groups for access control',
      'Restart netdata service',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://netdata.example.com/api/v1/auth/callback',
    configTemplate: {
      enabled: 'yes',
      oidc_discovery_url: 'https://opendirectory.local/.well-known/openid-configuration',
      client_id: '<CLIENT_ID>',
      client_secret: '<CLIENT_SECRET>',
    },
    documentationUrl: 'https://learn.netdata.cloud/docs/security-and-privacy-design/authentication',
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    logo: '🐻',
    category: 'Monitoring',
    protocol: 'oidc',
    description: 'OIDC login for Uptime Kuma self-hosted status page and monitoring.',
    setupSteps: [
      'Go to Uptime Kuma Settings → Security → OAuth2/OIDC',
      'Enable OIDC login',
      'Enter discovery URL, client ID, and client secret',
      'Set callback URL in OpenDirectory client registration',
      'Optionally restrict to specific groups',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://uptime.example.com/api/oidc-callback',
    configTemplate: {
      oidcDiscoveryUrl: 'https://opendirectory.local/.well-known/openid-configuration',
      oidcClientId: '<CLIENT_ID>',
      oidcClientSecret: '<CLIENT_SECRET>',
      oidcRedirectUrl: 'https://uptime.example.com/api/oidc-callback',
    },
    documentationUrl: 'https://github.com/louislam/uptime-kuma/wiki/OAuth2-Configuration',
  },
  {
    id: 'paperless-ngx',
    name: 'Paperless-ngx',
    logo: '📄',
    category: 'Productivity',
    protocol: 'oidc',
    description: 'OIDC via social-django for Paperless-ngx document management.',
    setupSteps: [
      'Install social-auth-app-django or django-allauth',
      'Add OIDC backend to AUTHENTICATION_BACKENDS',
      'Configure SOCIAL_AUTH_OIDC_* settings in paperless.conf',
      'Run migrations and restart',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://paperless.example.com/accounts/oidc/opendirectory/login/callback/',
    configTemplate: {
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect":{"APPS":[{"provider_id":"opendirectory","name":"OpenDirectory","client_id":"<CLIENT_ID>","secret":"<CLIENT_SECRET>","settings":{"server_url":"https://opendirectory.local"}}]}}',
    },
    documentationUrl: 'https://docs.paperless-ngx.com/configuration/#PAPERLESS_SOCIALACCOUNT_PROVIDERS',
  },
  {
    id: 'immich',
    name: 'Immich',
    logo: '🖼️',
    category: 'Media',
    protocol: 'oauth2',
    description: 'OAuth2/OIDC login for the Immich self-hosted photo management platform.',
    setupSteps: [
      'Go to Immich Administration → OAuth',
      'Enable OAuth login',
      'Enter issuer URL, client ID, and client secret',
      'Configure scope and button text',
      'Enable auto-register for new users',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://immich.example.com/auth/login',
    configTemplate: {
      issuerUrl: 'https://opendirectory.local',
      clientId: '<CLIENT_ID>',
      clientSecret: '<CLIENT_SECRET>',
      scope: 'openid profile email',
      buttonText: 'Login with OpenDirectory',
      autoRegister: true,
    },
    documentationUrl: 'https://immich.app/docs/administration/oauth',
  },
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    logo: '🔑',
    category: 'Security',
    protocol: 'oidc',
    description: 'SSO via OIDC for Vaultwarden (Bitwarden-compatible) password manager.',
    setupSteps: [
      'Set SSO_ENABLED=true in Vaultwarden env',
      'Set SSO_AUTHORITY to OpenDirectory issuer URL',
      'Set SSO_CLIENT_ID and SSO_CLIENT_SECRET',
      'Configure SSO_SCOPES',
      'Restart Vaultwarden',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://vault.example.com/identity/connect/oidc-signin',
    configTemplate: {
      SSO_ENABLED: 'true',
      SSO_ONLY: 'false',
      SSO_AUTHORITY: 'https://opendirectory.local',
      SSO_CLIENT_ID: '<CLIENT_ID>',
      SSO_CLIENT_SECRET: '<CLIENT_SECRET>',
      SSO_SCOPES: 'openid,profile,email',
    },
    documentationUrl: 'https://github.com/dani-garcia/vaultwarden/wiki/Single-Sign-On',
  },
  {
    id: 'authentik-federation',
    name: 'Authentik (Federation)',
    logo: '🌐',
    category: 'Identity',
    protocol: 'oidc',
    description: 'Configure OpenDirectory as OIDC upstream source for Authentik federation.',
    setupSteps: [
      'Go to Authentik Admin → Sources → Add OAuth Source',
      'Set Provider Type to OpenID Connect',
      'Enter OIDC Well-Known URL',
      'Configure Client ID and Secret',
      'Map claims to Authentik user fields',
    ],
    defaultScopes: ['openid', 'profile', 'email', 'groups'],
    defaultRedirectUriPattern: 'https://authentik.example.com/source/oauth/callback/opendirectory/',
    configTemplate: {
      providerType: 'openidconnect',
      authorizationUrl: 'https://opendirectory.local/oauth/authorize',
      accessTokenUrl: 'https://opendirectory.local/oauth/token',
      oidcWellKnownUrl: 'https://opendirectory.local/.well-known/openid-configuration',
      consumerKey: '<CLIENT_ID>',
      consumerSecret: '<CLIENT_SECRET>',
    },
    documentationUrl: 'https://goauthentik.io/docs/sources/oauth',
  },
  {
    id: 'custom-oidc',
    name: 'Custom OIDC App',
    logo: '🔧',
    category: 'Custom',
    protocol: 'oidc',
    description: 'Generic OIDC integration template for any standards-compliant application.',
    setupSteps: [
      'Register client in OpenDirectory to get Client ID and Secret',
      'Configure your app with the discovery URL',
      'Set the redirect URI in both app and OpenDirectory',
      'Request required scopes (openid, profile, email)',
      'Validate tokens using the JWKS endpoint',
    ],
    defaultScopes: ['openid', 'profile', 'email'],
    defaultRedirectUriPattern: 'https://myapp.example.com/callback',
    configTemplate: {
      discovery_url: 'https://opendirectory.local/.well-known/openid-configuration',
      client_id: '<CLIENT_ID>',
      client_secret: '<CLIENT_SECRET>',
      redirect_uri: 'https://myapp.example.com/callback',
      scope: 'openid profile email',
    },
    documentationUrl: 'https://openid.net/specs/openid-connect-core-1_0.html',
  },
  {
    id: 'custom-saml',
    name: 'Custom SAML App',
    logo: '📜',
    category: 'Custom',
    protocol: 'saml',
    description: 'Generic SAML 2.0 integration template for enterprise applications.',
    setupSteps: [
      'Download IdP metadata from /saml/metadata',
      'Import metadata into your SP configuration',
      'Set the ACS (Assertion Consumer Service) URL in OpenDirectory',
      'Configure attribute mappings for user fields',
      'Test SSO flow with a test account',
    ],
    defaultScopes: [],
    defaultRedirectUriPattern: 'https://myapp.example.com/saml/acs',
    configTemplate: {
      idp_metadata_url: 'https://opendirectory.local/saml/metadata',
      idp_sso_url: 'https://opendirectory.local/saml/sso',
      idp_slo_url: 'https://opendirectory.local/saml/slo',
      attribute_email: 'email',
      attribute_username: 'preferred_username',
    },
    documentationUrl: 'https://docs.oasis-open.org/security/saml/v2.0/saml-technical-overview-2.0-cd-02.html',
  },
];

module.exports = { APP_CATALOG };
