#!/bin/bash
set -euo pipefail

# Samba AD DC Domain Provisioning Script
# Called by Node.js API to provision a new Samba AD DC domain
# Usage: provision-domain.sh <REALM> <DOMAIN> <ADMIN_PASSWORD> <DNS_BACKEND> [SERVER_ROLE]

REALM="${1:?Realm is required (e.g., OPENDIRECTORY.LOCAL)}"
DOMAIN="${2:?Domain is required (e.g., OPENDIRECTORY)}"
ADMIN_PASSWORD="${3:?Admin password is required}"
DNS_BACKEND="${4:-SAMBA_INTERNAL}"
SERVER_ROLE="${5:-dc}"

LOG_FILE="/var/log/opendirectory/provision-$(date +%Y%m%d-%H%M%S).log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

error_exit() {
    log "ERROR: $1"
    exit 1
}

validate_inputs() {
    # Validate realm format (must be UPPERCASE with at least one dot)
    if ! echo "$REALM" | grep -qE '^[A-Z][A-Z0-9.-]+\.[A-Z]{2,}$'; then
        error_exit "Invalid realm format. Must be uppercase FQDN (e.g., OPENDIRECTORY.LOCAL)"
    fi

    # Validate domain (NetBIOS name, max 15 chars, uppercase)
    if ! echo "$DOMAIN" | grep -qE '^[A-Z][A-Z0-9]{0,14}$'; then
        error_exit "Invalid domain name. Must be uppercase NetBIOS name, max 15 characters"
    fi

    # Validate DNS backend
    if [[ "$DNS_BACKEND" != "SAMBA_INTERNAL" && "$DNS_BACKEND" != "BIND9_DLZ" ]]; then
        error_exit "DNS backend must be SAMBA_INTERNAL or BIND9_DLZ"
    fi

    # Validate password complexity
    if [ ${#ADMIN_PASSWORD} -lt 8 ]; then
        error_exit "Admin password must be at least 8 characters"
    fi
}

backup_existing_config() {
    local backup_dir="/var/backups/samba/pre-provision-$(date +%Y%m%d-%H%M%S)"
    if [ -f /etc/samba/smb.conf ]; then
        log "Backing up existing Samba configuration..."
        mkdir -p "$backup_dir"
        cp /etc/samba/smb.conf "$backup_dir/" 2>/dev/null || true
        cp /etc/krb5.conf "$backup_dir/" 2>/dev/null || true
    fi
}

stop_conflicting_services() {
    log "Stopping conflicting services..."
    systemctl stop smbd nmbd winbind 2>/dev/null || true
    systemctl disable smbd nmbd winbind 2>/dev/null || true

    # Remove default smb.conf that blocks provisioning
    if [ -f /etc/samba/smb.conf ]; then
        mv /etc/samba/smb.conf /etc/samba/smb.conf.bak
    fi
}

provision_domain() {
    log "Provisioning Samba AD DC domain..."
    log "  Realm: $REALM"
    log "  Domain: $DOMAIN"
    log "  DNS Backend: $DNS_BACKEND"
    log "  Server Role: $SERVER_ROLE"

    samba-tool domain provision \
        --realm="$REALM" \
        --domain="$DOMAIN" \
        --server-role="$SERVER_ROLE" \
        --dns-backend="$DNS_BACKEND" \
        --adminpass="$ADMIN_PASSWORD" \
        --use-rfc2307 \
        --option="interfaces=lo eth0" \
        --option="bind interfaces only=yes" \
        2>&1 | tee -a "$LOG_FILE"

    if [ ${PIPESTATUS[0]} -ne 0 ]; then
        error_exit "Domain provisioning failed"
    fi

    log "Domain provisioned successfully"
}

configure_kerberos() {
    log "Configuring Kerberos..."
    local realm_lower=$(echo "$REALM" | tr '[:upper:]' '[:lower:]')

    # Copy the Kerberos config generated by Samba
    if [ -f /var/lib/samba/private/krb5.conf ]; then
        cp /var/lib/samba/private/krb5.conf /etc/krb5.conf
        log "Kerberos configuration installed"
    else
        # Create a manual krb5.conf
        cat > /etc/krb5.conf << KRBEOF
[libdefaults]
    default_realm = $REALM
    dns_lookup_realm = false
    dns_lookup_kdc = true
    rdns = false

[realms]
    $REALM = {
        kdc = $(hostname -f)
        admin_server = $(hostname -f)
        default_domain = $realm_lower
    }

[domain_realm]
    .$realm_lower = $REALM
    $realm_lower = $REALM
KRBEOF
        log "Kerberos configuration created manually"
    fi
}

configure_dns() {
    log "Configuring DNS resolution..."

    # Point local resolver to Samba DNS
    cat > /etc/resolv.conf << DNSEOF
nameserver 127.0.0.1
search $(echo "$REALM" | tr '[:upper:]' '[:lower:]')
DNSEOF

    log "DNS resolution configured"
}

setup_sysvol() {
    log "Setting up SYSVOL replication directories..."
    local realm_lower=$(echo "$REALM" | tr '[:upper:]' '[:lower:]')
    local sysvol_path="/var/lib/samba/sysvol"

    # Ensure proper permissions
    chmod -R 755 "$sysvol_path" 2>/dev/null || true
    chown -R root:root "$sysvol_path" 2>/dev/null || true

    # Create default GPO directories if not present
    mkdir -p "$sysvol_path/$realm_lower/Policies" 2>/dev/null || true
    mkdir -p "$sysvol_path/$realm_lower/scripts" 2>/dev/null || true

    log "SYSVOL directories configured"
}

verify_provisioning() {
    log "Verifying domain provisioning..."

    # Check smb.conf exists
    if [ ! -f /etc/samba/smb.conf ]; then
        error_exit "smb.conf not found after provisioning"
    fi

    # Check SYSVOL
    local realm_lower=$(echo "$REALM" | tr '[:upper:]' '[:lower:]')
    if [ ! -d "/var/lib/samba/sysvol/$realm_lower" ]; then
        error_exit "SYSVOL directory not created"
    fi

    # Check private directory
    if [ ! -f /var/lib/samba/private/sam.ldb ]; then
        error_exit "SAM database not created"
    fi

    log "Domain verification passed"
}

write_status() {
    local realm_lower=$(echo "$REALM" | tr '[:upper:]' '[:lower:]')
    cat > /var/lib/samba/.opendirectory-status << STATUSEOF
{
    "provisioned": true,
    "realm": "$REALM",
    "domain": "$DOMAIN",
    "dnsBackend": "$DNS_BACKEND",
    "serverRole": "$SERVER_ROLE",
    "provisionedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "hostname": "$(hostname -f)",
    "sysvolPath": "/var/lib/samba/sysvol/$realm_lower"
}
STATUSEOF
    log "Status file written"
}

# Main execution
main() {
    log "=========================================="
    log "Samba AD DC Domain Provisioning"
    log "=========================================="

    validate_inputs
    backup_existing_config
    stop_conflicting_services
    provision_domain
    configure_kerberos
    configure_dns
    setup_sysvol
    verify_provisioning
    write_status

    log "=========================================="
    log "Domain provisioning completed successfully"
    log "=========================================="
    log "You can now start Samba with: samba -F"
}

main
