[supervisord]
nodaemon=true
logfile=/var/log/opendirectory/supervisord.log
pidfile=/var/run/supervisord.pid

[program:samba]
command=/usr/sbin/samba -F --no-process-group
autostart=true
autorestart=true
stdout_logfile=/var/log/samba/samba-supervisor.log
stderr_logfile=/var/log/samba/samba-supervisor-err.log
priority=10

[program:node-api]
command=node /app/src/index.js
autostart=true
autorestart=true
stdout_logfile=/var/log/opendirectory/api.log
stderr_logfile=/var/log/opendirectory/api-err.log
environment=NODE_ENV="production"
priority=20
